services:
  nginx-gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-service

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"

  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #ports:
    # - "5432:5432"

volumes:
  postgres_data:
